---
title: "Mobile Multimodal Lab"
subtitle: "Introduction"
authors: Davide Ahmar,  Wim Pouw, Šárka Kadavá
---

# Introduction 

In recent years the research landscape in cognitive science has changed dramatically. Technological and methodological advancements in sensing equipment, recording devices and computational tools that handle high-dimensional data have paved the way for a new era of behavioral research, moving several interdisciplinary fields from unimodal to multimodal approaches (e.g., see Turk, 2014; Yang, 2019) for reviews). In the last decade alone, more than 60 thousand scientific publications have appeared with the term “multimodal” in their keywords, marking a 400% increase from the previous decade (source: Scopus, 2025). In contrast to the past, where measurements were limited to either unimodal proxies or laborious manual labelling of observed behaviors (e.g., Brugman & Russel, 2014.), nowadays researchers can employ state-of-the-art motion tracking systems [e.g., “Vicon”, Pfister et al., 2014) or OptiTrack, Nagymáté & Kiss, 2018)] alongside high-frequency sensing devices [e.g., wereable eye trackers, (Gunawardena et al., 2022)or electrophysiological recordings (Moon & Lee, 2023)] to simultaneously capture movements, speech, physiological changes, gaze patterns, and even neural states, as they unfold in real time. For instance, combined electroencephalographic, kinematic and eye-tracking recordings can reveal the intra- and inter-personal brain-behavior dynamics of phenomena such as neural synchrony (e.g., (Koul et al., 2023), cognitive workload (e.g., Charles & Nixon, 2019) or psychosocial stress (e.g., Richer et al., 2024). Accordingly, the progress in technological infrastructures has yielded a similar progress in the level of spatio-temporal granularity with which researchers can ask and answer questions about different neuro-cognitive-behavioral phenomena.

Despite these technological advancements, there are important methodological challenges that will shape the future directions of this emerging field. To start, building a functioning multimodal laboratory from scratch can be both technically complex and prohibitively costly for many researchers. Firstly, one needs to select the appropriate recording system for each modality, a choice that can be particularly overwhelming given the sheer number of different manufactures, pricing ranges and technical specifications. For instance, there are currently dozens of commercially available motion tracking (MT) systems, spanning a wide range of technologies – from high-precision optical systems (e.g., Vicon, Qualisys) to wearable inertial sensors (e.g., Xsen, Noraxon), and from markerless computer vision tools (e.g., OpenPose, MediaPipe) to pressure-based platforms (e.g., AMTI force plates) –  and costing from few hundred (e.g., standard USB cameras) to hundreds of thousands euros (e.g., e.g., multi-camera Vicon system). Secondly, assembling all multiple recording devices (MT, microphones, physiological sensors, etc.) in a spatially efficient and modular setup without interfering with participants natural behaviors poses design and logistical challenges. For instance, many commercially available setups are only tailored to fixed laboratory environments, rely on heavy infrastructure, and are primarily designed for single-participant recordings, making them difficult to relocate or adapt the laboratory to real-world settings and/or multiple participants (ref). Thirdly, once all the equipment are selected and installed, a major challenge lies in integrating and synchronizing the heterogeneous data streams they produce. Each modality – whether MT, audio, gaze or physiology – is sampled at different rates (with differences in the ranges of 20X), recorded using different hardware and software, and encoded in different formats (ref). Ensuring that all these signals are temporally aligned with sufficient precision and stored in an integrated and accessible format is non-trivial, especially in studies involving many recordings devices in highly naturalistic paradigms with multiple interacting participants. Finally, even after data collection, researchers are faced with the substantial demands of managing and analyzing multi-dimensional, time-varying datasets —such as dozens of 2D video streams, high-resolution audio, and continuous physiological signals—all of which need to be pre-processed, and organized for analysis. Without standardized pipelines or centralized data structures, this process can become fragmented and error-prone, especially when integrating data from multiple participants or sessions (ref). 

In most cases, researchers have outsourced these challenges to proprietary companies that manufacture recording systems, software and analyses packages. For instance, when choosing the right equipment to capture participants movements, one might opt for a state-of-the-art MT system from a proprietary company (e.g., such as Vicon or Qualysis) that offers extensive customer support (including installation), optimal recording accuracy, and a user-friendly software with built-in analyses packages (Merriaux et al., 2017). While these proprietary solutions offer clear advantages, they also come with some important drawbacks. In fact, these systems are often prohibitively expensive (e.g., Qualisys: circa 150-200K €, Vicon: 200-250K €) and rely on proprietary licensing (often with monthly subscriptions costs) with closed-sourced software and analyses toolkits (ref). As a result, they are not accessible to many researchers working with limited budgets, nor easily adaptable for use in non-standard experimental setups or in field-based research. Additionally, even when the budget allows, one is still left with the pressing issue of integrating and synchronising motion data with other data streams that themselves might come from  different proprietary systems, as each device/software only records its own modality with its specified sampling rate and data format.  

Given this context, the field of multimodality is facing a crossroad, or at least faces the challenge to build multiple roads of discovery: on the one hand we could rely primarily on proprietary and expensive systems, or we can invest and build intellectual capital to move towards more affordable and opensource alternatives. Continuing with the former path has clear advantages for well-funded labs that can afford the high costs, but it inevitably excludes under-resourced labs, early-career researchers, or institutions in low- and middle-income countries. Beyond the issue of access, this reliance on closed commercial ecosystems inherently restricts the dissemination of knowledge between the many interdisciplinary groups involved in multimodal research, concentrating the technical expertise behind paywalls and within select manufactures or labs. In contrast, the path of affordable and opensource solutions aims to democratize access to multimodal research, making both the tools and the underlying technical knowledge openly available to anyone interested in using them. This approach has the potential to shape the field into a more equitable, transparent and collaborative scientific ecosystem where researchers engage open pedagogical practices and actively contribute to the development, adaptation, and dissemination of methodological tools.

Here we introduce  Mobile Multimodal Laboratory (MMLab). Developed within the Donders institute for Brain, Cognition and Behavior, the MMLab project aims to provide an affordable, open-source solution to anyone interested in capturing multimodal human behaviors in both controlled and ecological environments. It includes suite of freely available resources – that include the present paper, an extensive coding library, and a quarto-based manual – designed to guide users through the process of building a multimodal setup, including synchronizing, recording, and analysing data streams of interest. The MMLab was built around the following key features:  

Accessibility: all documentation, code, and tutorials are open sourced to ensure broad accessibility, transparency, and reuse across research communities.
Affordability: the proposed setup can be fully assembled for under 10,000€, as it relies on low-cost components and, whenever possible, non-proprietary hardware and software.
Portability: MMLab is designed to be compact and easily transportable, allowing researchers to deploy it a range of testing environments beyond traditional lab spaces.
Built-in Integration and Synchronization: data from each recording device is centrally integrated through the Lab Streaming Layer (LSL, ref), which allows for precise temporal synchronization of multimodal steams.
Modularity: the setup supports a wide range of interchangeable components and sensors compatible with LSL, allowing researchers to customize the lab to suit specific research goals.
Adaptability: ?

The present paper serves both as an introductory guide and a step-by-step tutorial designed to walk researchers and technical staff through the process of assembling and operating the MMLab. To illustrate each step, we grounded our guide in a proof-of-concept experiment in which two participants engaged in an interpersonal singing task while being simultaneously recorded across multiple 2D video streams (e.g., for 3D motion tracking), high-frequency microphones (e.g., for prosodic or semantic analyses) and wireless physiological recordings (e.g., ECG, EMG and respiration). All these heterogeneous data streams were integrated and synchronized using the LSL system (ref), an opensource middleware that allows centralized data collection with sub-millisecond synchronization. Our specific experimental configuration is intended as a “default” setup that can be adapted to meet individual research needs and evolving technological capabilities, as other recording devices - such as EEG or eye-tracking – can easily be incorporated into the pipeline, provided they are compatible with the Lab Streaming Layer (LSL). The accompanying coding library and quarto-based manual includes all necessary coding steps and technical details for hardware configuration, synchronization, preprocessing, and multimodal analysis—providing researchers with a complete, ready-to-adapt pipeline.


## Structure of the tutorial
The tutorial provides a detailed, step-by-step guide on how to (i) set up, (ii) preprocess, and (iii) analyze the multimodal data recorded with the MMLab, grounding these procedures in our proof-of-concept experiment.  Following a brief overview of this experimental design, the Methods section is structured into three main parts: 
Experimental design
Setup of the MMLab: This part outlines the specific hardware and software components used in our MMLab, detailing the rationale for choosing our equipment, the steps involved in assembling the components, the recording procedures for each modality, and the integration within the LSL system. 
Preprocessing of Multimodal Data: This section explains all the steps required to prepare the recorded multimodal data for analysis. Based on the original scripts in our library (ref), here we describe the procedures for extracting data streams from the unified recording file, synchronizing these multimodal streams, and segmenting and clipping data into manageable intervals for subsequent analysis. 
Multimodal Signal Processing and Analysis. In progess..

Alongside the manuscript, we also provide online manual available at https://multimoblab.github.io/Mobile-Multimodal-Lab/ . The online manual is an extended copy of this manuscript; it provides technical details where necessary and scripts that enable implementions of all steps. Unlike this manuscript, it is meant to be regularly updated to resolve any issues or accommodate wishes of MMLab users.

## How to use the tutorial

xxxx

## Proof-of-concept experiment
Our proof-of-concept experiment investigates the role of interpersonal synchrony that emerges across multiple modalities (namely vocal output, bodily movements and physiological responses) during a structured singing task. We opted for such paradigm because musical interactions offer a wealth of intra-and-inter-personal dynamics unfolding across different behavioral and physiological channels. For instance, research on music cognition has shown that the perception of and synchronization with musical structure are shaped by multiscale influences, including physiological states (Vickhoff et al., 2013), bodily moments (Toiviainen et al., 2010), psychological traits (Novembre et al., 2019), and processes of musical enculturation (Hannon & Trainor, 2007). Additionally, at a methodological level, this kind of research requires recording of brain/body signals during active behaviors in naturalistic settings. This makes it particularly well suited for a mobile multimodal setup that can bring its experimental infrastructure to participants, rather than requiring them to adapt to highly constrained laboratory environments. Crucially, this mobility and multimodality needs to be achieved without sacrificing precision in the recordings, and our MMLab setup enables tightly synchronized recordings at both intra-personal (e.g., heart rate, muscle activity) and inter-personal (e.g., gestural coupling) levels.


