---
title: "Untitled"
format: html
---


# Method I: Experimental design and procedure

Two participants engaged in a joint singing task within a two-by-two factorial design, manipulating the (1) visual access between participants (Vision vs. NoVision) and the (2) freedom of movement (Movement vs. NoMovement), as depicted in Figure 1, A. A custom python script handled the presentation of auditory stimuli, the timing of each experimental phase, and the streaming of event markers via LSL. 
[Quarto: here is script for presentation of stimuli]
Each of the four conditions (Vision_Movement, Vision_NoMovement, NoVision_Movement, NoVision_NoMovement) was presented in a random order and consisted of five structured trials: after a keyboard press to initiate the condition and relay the marker to the LSL, participants listened to a set of synthetic melodies composed of five randomized MIDI notes that had been created in advance to standardize pitch, duration, and temporal structure. Following the audio presentations, participants were instructed to vocally reproduce the melodies in synchrony with each other during a 10 second interval delimited by start-and-end auditory beeps.
Following this design, we expected that the Vision_Movement condition to yield the highest levels of vocal synchrony, as visual access and freedom of movement allow participants to couple both motor and vocal-acoustic systems during interaction. However, because this experiment was designed solely to demonstrate the MMLab’s functionality, we did not focus on formal hypothesis testing nor specific outcome measures. Rather, our pipeline was structured such that this placeholder paradigm can be replaced with any experimental design involving one or more participants and two or more data streams.  
