---
title: "Mobile Multimodal Lab"
subtitle: "Methods: Lab Setup"
authors: Davide Ahmar,  Wim Pouw, Šárka Kadavá
---

# Lab setup 

This section provides a practical guide on how to assemble each component used in our MMLab default setup, along with the procedures for operating the recording systems during data acquisition. As mentioned in the introduction, our choices of equipment were guided by the principles of (1) accessibility, (2) affordability, (3) portability, (4) integration and (5) modularity. Importantly, we do not endorse any particular manufacturer and, although we describe the exact brands models used in our setup, alternative components can be substituted provided they meet similar technical specifications. An overview of the full lab configuration, including a depiction of the experimental design, is provided in Figure 1. In what follows, we first elaborate on the data streams and recording devices included in the current version of MMLab; and finish with integration of all streams under one central clock via LabStreamLayer (LSL).

[Figure]

Figure 1. Overview of experimental design, MMLab setup and equipment specifications.  (A) Experimental design depicting the 2x2 factorial design in the structured singing task. In the Vision conditions (most-left, middle-left) participants face each other directly, whereas in the NoVision conditions (middle-right, most-right) a visual barrier prevents mutual visual access. In the Movement conditions (most-left, middle-right), participants are free to move naturally while singing, whereas in the NoMovement conditions (middle-left, most-right) they are instructed to remain still. (B) Illustration of the MMLab setup used in the experiment. Each participant is recorded by three frame-synchronized cameras (Video: blue lines, wired to a Window-based PC), a head-mounted microphone (Audio: red lines, wired to amplifier and a Linux-based mini PC), two electromyographical sensors, one electrocardiogram sensor and one respiration belt (Physiology: purple dashed lines, wireless Bluetooth transmission to the Windows PCs). The Video and Physiology streams from the two Windows PCs and the Audio streams from the two Linux mini-PCs were integrated over a wired local network LSL system (Lab Steaming Layer: green, wired to a third Windows-based PC). (C) Equipment specifications and pricing information for the LSL (top, green), Video (bottom, blue), Audio (left, red) and Physiology (right, purple). 

## Video
**Choosing the Video Recording Setup:** The MMLab camera setup is primarily optimized for video-based, whole-body 3D motion tracking (MT). Thanks to rapid advancements in motion analysis technologies and fueled by growing interest across research and clinical domains, there are many MT systems available on the market, each offering distinct strengths and trade-offs (for a comprehensive review of different systems see van Schaik & Dominici, 2020) . For our MML setup, we opted for a video-based MT system (with computer vision models for pose-estimations) rather than device-based systems (which use dedicated sensors to capture movement), since it best aligns with our five core requirements. In fact, while device-based systems (e.g.,Vicon or Qualysis) can reach sub-millimeter accuracy, they come at a steep financial cost (typically > €100,000 or more for full systems, (van der Kruk & Reijne, 2018; van Schaik & Dominici, 2020). In contrast, video-based systems using consumer-grade cameras can be implemented for under €1,000, making them orders of magnitude more affordable. Importantly, affordable video-based MT systems still maintain high levels of precision that are sufficient for most behavioral studies, with minimal loss of accuracy compared to state-of-the-art device-based systems (for performance comparisons between video-based and device-based systems, see Koul & Novembre, 2025; Martini et al., 2022; Ota et al., 2020; Pouw et al., 2020). 
Additionally, the free and open source nature of most computer vision models that are used to extract full-body pose estimates from standard RGB video recordings - such as OpenPose (Cao et al., 2019) Mediapipe (Lugaresi et al., 2019) - has dramatically improved the accessibility of MT research for many researches that do not have access to proprietary hardware (and their black-boxed software). Finally, in contrast to the complex, expensive-to-insure, and sometimes bulky nature of device-based motion tracking systems, video-based setups in contrast can consist of lightweight, portable components (e.g., USB-cameras, foldable tripods, and a laptop), making them ideal for mobile research settings and, notably, particularly suitable for studying diverse populations like human infants and non-human animals, as they do not require wearable sensors or body markers.  

**Video-recording Equipment:**  The video-recording setup of MMLab comprises six USB cameras mounted on two movable arches, with three cameras assigned to (i.e., facing) each participant. Each three-camera arch was connected to a dedicated recording computer (Dell Precision 3640 Tower) to manage the video streams independently. To improve portability, the camera arches can be replaced with foldable tripods provided that each camera remains fixed during recording and positioned approximately at the participants’ head height across all sessions. Although a single front-facing camera is sufficient for basic 2D body pose estimation, using three simultaneous viewpoints allows for more robust pose extraction and, importantly, triangulation in 3D space. For the cameras, here we chose the “Elgato Facecam” (link?) as they best aligned with our principles. Each unit is relatively inexpensive (~€120), lightweight (96 g), capable of recording in full-HD resolution (1080p) at 60 Hz, and comes with a free software (Elgato Hub, link?) that allows for adjusting camera settings. Crucially, it also has adjustable shutter speed (up to 1/250s), which is an important component for motion tracking, as lower shutter speeds (below 1/100s) tend to introduce motion blur and, therefore, can impair pose estimation accuracy. Naturally, other camera models can be substituted, as long as they allow for adjustable shutter speeds reaching above 1/100s.
Quarto only: See here for shutter speed analyses. 

::: {.content-visible when-format="html"}

:::

Quarto only: see here for more information on the camera and computer equipment 
Each trio of cameras was fed to a Windows PC equipped with a multi-core processor (e.g., Intel i7 or equivalent) capable of encoding and processing the three video streams in parallel. To prevent bandwidth overload and reduce the risk of dropped frames, two of camera-to-PC connections were mediated by a powered USB hub and distributed across separate USB buses wherever possible (e.g., by allocating one camera to a USB 3.0 port and the remaining cameras to separate USB 2.0 controllers).  The use of a powered hub also provided stable external power to the cameras and reduced voltage drop across longer cable runs, minimizing video frame loss. 

**Video Recording Procedures:** Before recordings, each camera setting was manually configured through the Elgato Camera Hub software to ensure optimal conditions for MT. Specifically, we set the shutter speed to 1/200s to reduce motion bur, downsampled the image resolution to qHD (960 × 540) to minimize data storage demands, and fixed the ISO at 354 to stabilize image brightness and contrast under short exposure times. 

::: {.content-visible when-format="html"}
Screenshot from Elgato
:::


To simultaneously capture the three frame-synced videos from each camera trios in the two recordings PC and stream the corresponding time-stamped frames to the LSL, we used a custom Python script by Kadavá and Pouw (2024). This script leverages the OpenCV (Bradski, 2000) and FFmpegCV (ref?) libraries to feed the combined side-by-side videos from the three cameras into a single compositive video using multithreading, which ensured that all frames were synchronized for each sampling timepoint. The video was recorded at 60 Hz in an uncompressed format to preserve image fidelity during acquisition. Importantly, the script also integrated the videos with the LSL using the PyLSL library (Kothe, 2014), which generates an LSL stream containing a running frame index value f(t) paired with common LSL timestamp t aligned with all the others recording modalities.

::: {.content-visible when-format="html"}
Camera script
:::

After each session, the raw videos were compressed using the XVID codec at a 2.5x reduction ratio to ease data transfer and storage space. 


**Camera Calibration Procedures:** To ensure 3D pose estimation from multi-angle recordings, video-based MT algorithms require prior information on the intrinsic parameters (e.g., focal length, distortion coefficients) and extrinsic parameters (i.e., spatial orientation and position relative to other cameras) of each device (for more information, see Karashchuk et al., 2021). Therefore, before each recording, we performed a calibration procedure for each trio of cameras assigned to a participant. Specifically, we recorded a short (∼1-minute) calibration video using a ChArUco calibration board (see Figure 1 C) that was moved systematically throughout the full vertical and horizontal space later occupied by the participant during the experiment. These calibration videos were then used to compute the geometric parameters for 3D triangulation during MT (see Section X – Motion Capture Analysis).

::: {.content-visible when-format="html"}
Calib picture
:::


## Audio Recordings
Choosing the Audio Recording Setup: While both device-based MT systems and commercially available cameras typically include built-in microphones, the audio quality of these microphones is typically insufficient for high-resolution analyses of speech features such as pitch, intensity and prosody(Švec & Granqvist, 2010) . Therefore, to obtain a good level of acoustic fidelity, in our MMLab we opted for a high-quality, head-mounted condenser microphone recording independently from the cameras. This design ensured consistent mouth-to-mic distance, reduced ambient interference, and reliable amplitude and frequency tracking across sessions. Additionally, to stream the audio signal to the LSL, we preferred a Linux-based PC over Windows or macOS because it enabled real-time streaming of low-latency, high precision audio thanks to its Advanced Linux Sound Architecture (ALSA). 

**Audio Recording Equipment:** For the microphone, we employed a professional-grade, head-mounted condenser microphone (model: AKG C520, price ~€250) for each participant, as shown in Figure 1 C. The head-mounted configuration was important for maintaining a fixed distance between the participant’s mouth and the microphone capsule (essential for measurement of speech amplitude and prosodic features), whilst the cardioid polar pattern further focused sensitivity toward the speaker’s mouth and rejected off-axis environmental noise. Additionally, its built-in shock-mount system helped reduce the mechanical noise generated by body movements. Both microphones were powered via a XLR connection to a DAP PRE-202 low-noise, 2-channel digital amplifier (price: ~€90), which provided a +48V phantom power and included a low-cut filter to suppress low-frequency ambient noise. Input gain on the amplifier was manually fixed at 25% across all recordings to standardize signal levels. From the amplifier, the signal from each microphone was routed via two XLR-to-USB interface to two MINIX NEO z83-4 MAX Linux-based mini-PC (price: ~€170). 

**Audio Recording Procedures:** To record and stream participants’ audio to the LSL, we used a custom-made Python script developed in collaboration with Technical Support Group (TSG) at the Donders Institute. 

::: {.content-visible when-format="html"}
Script for audio
:::

The script was executed on each MINIX Linux device and utilized the alsaaudio library to record each signal in mono at a sampling rate of 16 kHz, with 16-bit little-endian encoding optimized for low-latency buffering. The audio data from each MINIX was then streamed to the LSL using the pylsl library (Kothe, 2014), pushing small chunks of 160 data points timestamped against the system clock. The LSL then used the declared sampling rate and local system clock to reconstruct sample timing, allowing synchronization with other multimodal streams at sub-millisecond resolution. Additionally, to ensure data quality before acquisition, we used a secondary Python script that allowed for real-time graphic visualization of the incoming audio stream. This script pulled the audio data back from LSL and plotted it on a live display that was continuously updated, enabling to verify waveform quality and monitor for issues such as noise artifacts, clipping, or dropouts. 
[Quarto: audio signal visualizing script]

## Physiological Recordings
Choosing the Physiological Setup: To complement the audio-visual modalities in our MMLab setup, we also included physiological recordings of the EMG activity from participants’ biceps and triceps and thoracic respiration, with the goal of quantifying interpersonal physiological synchrony. Here, we wanted to prioritize a system that could support a modular sensor architecture, allowing researchers to buy only the biosensors relevant to their experimental goal. Additionally, we opted for a system that could transmit these signals wirelessly, thus granting participants free movements during the recordings. Finally, we needed something that could be easily integrated within the LSL system to ensure temporal synchronization with the other measures. Among all the avaliable proprietary options, we chose “PLUX Biosignals” recording system as it seemed to meet all these requirements and offered a strong price/quality balance.

Physiological Recording Equipment: As shown in Figure 1C, the equipment consisted of two (one per participant) “biosignalplux Hub” (price: ~€2000), each supporting up to 4 input channels and capable of sampling at rates of up to 3000 Hz per channel with 16-bit resolution (Note that an 8-channel biosignalplux Hub is also available, costing ~€4000). These devices transmitted data wirelessly via bluetooth in real time to their respective recording computers (the same used for video recordings) using a dedicated bluetooth dongle. To record participants’ muscle activity, we used two surface EMG sensors per participant (price ~€170), one placed over the biceps brachii and one over the triceps brachii of the right arm, allowing us to monitor the activation patterns of both flexor and extensor muscle groups. Prior to electrode placement, the skin was cleaned with an alcohol-based wipe and prepared using abrasive conductive gel (Nuprep) to reduce impedance and enhance signal quality. The electrodes were positioned in a bipolar configuration and aligned with the longitudinal axis of each target muscle. The EMG sensors operated in a bipolar differential configuration using two adhesive electrodes (positive and negative A separate reference (ground) electrode was placed on the participant’s olecranon of the right elbows bone with minimal muscle activity to reduce baseline noise. For cardiac activity, we used the biosignalplux ECG sensor configured for single-lead acquisition in the Einthoven triangle configuration, with the positive electrode placed on the left arm, negative on the right arm and ground on the left leg. To record respiratory patterns, we used a piezoelectric respiration sensor (PZT; price ~€170) per participant, secured around the upper thorax using an adjustable elastic strap. The sensing element was positioned centrally over the sternum. The strap was adjusted to ensure firm contact without restricting breathing. The sensor measured thoracic expansion and contraction during inhalation and exhalation via a flexible strip containing a centrally embedded piezoelectric sensing membrane.

Physiological Recording Procedures: Signal acquisition and LSL integration was managed using the OpenSignals (r)evolution software from biosignalsplux. Using the GUI of the software, we configured the EMGs and PZT channels to sample at 1000 Hz and visualized these signals in real time to verify signal-to-noise ratio and appropriate signal amplitude across EMG, ECG and respiration channels.
The data streams were then broadcasted directly to the LSL using the software’s built-in LSL integration (see documentation here), resulting in two streams (one per participant) each containing the two raw EMG and one PZT time series synchronized with the other data modalities. 

## Integration via Lab Streaming Layer (LSL)

**Choosing the Integration Setup:** A major challenge in multimodal research relates to synchronization and integration of different recordings that operate on distinct hardware platforms, communicate via different software interfaces, rely on independent systems clocks, and sample at different frequencies. Traditionally, synchronization of multimodal streams has been done post-recording by aligning common timestamped marker acquired during recordings for each modality. However, this approach relies on multiple independent recording computers with device-specific scripts for sending and receiving markers, resulting in decentralized data storage across systems. All of this increases the technical overheard as well as the manual effort during post-alignment. Additionally, even minor issues like latency differences or hardware incompatibilities can introduce significant lags that can easily mis-align the time series, often without any knowledge from the experimenters. For instance, video recordings are prone to dropped frames during acquisition, which, unless properly accounted for by timestamping each frame, can result in de-synchronization that is difficult to detect and correct post hoc.
To address these issues, in our MML we decided to implement the Lab Streaming Layer (Kothe et al., 2025) an open-sourced, cross-platform middleware system designed to enable real-time, sub-millisecond synchronization of heterogeneous data streams recorded from different devices. Unlike marker-based synchronization, the LSL creates a shared time base across all incoming data streams using each device’s local monotonic clock. This allows for all the streams to be synchronized at the time of recording and stored in a centralized data format. In addition, LSL is free-to-use, open-source, portable and highly modular, supporting a wide range of recording devices either through native compatibility (like the biosignalsplux device) or via custom-built LSL “outlet” scripts that stream data into the shared time framework (like our video and audio recording scripts). 


**LSL Equipment and Assembly:** At a system level, the LSL consists of the core liblsl library (Stenner et al., 2022) - a cross-platform API running working on Windows, macOS, and Linux - and associated GUI applications such as the LabRecorder (Kothe et al., 2025). Functionally, the LSL is built on a simple architecture of Outlets and Inlets. Each recording device broadcasts its stream (i.e., Outlet) via built-in system or via custom-made scripts in the form of descriptive metadata (e.g., stream name, content, type, number of channels, etc.). The receiving application (i.e., Inlet), such as LabRecorder, automatically detect these streams and records them in real time. To achieve multimodal synchronization, the LSL leverages each machine’s local monotonic clock and continuously performs clock offset estimation between the Outlet and Inlet through periodic pinging, which are then used to created a shared time based across all streams with sub-millisecond alignment. This software architecture must be physically implemented through a local network, that can span multiple PC’s. 
As shown in Figure 1B–C, our setup comprised two Windows PCs, each connected to three wired video cameras and wireless physiological sensors, and two Linux mini PCs, each connected to a wired audio stream. A third Windows PC was then used to centrally record all these synchronized data streams using the LSL’s LabRecorder. All machines were interconnected via a wired Gigabit Ethernet local area network (LAN) using a shared 5-port Gigabit switch (model used: NETGEAR GS305v3).  


**LSL Recording Procedures:**  The two Window PCs and the two Linux mini PCs functioned as an LSL Outlets, broadcasting their respective data stream over the local network via custom made scripts or native software integration as described in the methods above. The LabRecorder computer acted as the LSL Inlet, detecting and resolving all available streams. For the audio and physiological modalities, the full time-series data samples (together with their metadata) were transmitted via LSL and recorded directly into an Extensible Data Format (.xdf)file. In contrast, for the video modality, only the frame-level metadata were streamed via LSL. This entailed that each video frame was associated with a corresponding LSL timestamp and frame index, synchronized with the other modalities. The raw video files themselves were instead recorded locally on their respective Windows PCs
Prior to each recording, the LabRecorder graphical interface allowed us to check the presence of all expected streams from both participants. Once confirmed, recording was initiated through the LabRecorder interface, resulting in a single .xdf file, containing the audio, two EMGs, ECG, and respiration timeseries (with metadata) and combined three-videos metadata for each participant under a shared time base with sub-millisecond alignment.

::: {.content-visible when-format="html"}
Bash for installation
Screenshot Labrecorder
:::
