project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!/00_RAWDATA"
    - "!/Miscellaneous"
    - "!/shign"

website:
  sidebar:
    style: "floating"
    search: true
    contents:
      - text: "Home"
        href: index.qmd

      - section: "Lab Setup"
        contents:
          - text: "Overview"
            href: Labsetup_overview.qmd
          - text: "Video Recordings"
            href: Equip_video.qmd
          - text: "Audio Recordings"
            href: Equip_audio.qmd
          - text: "Physiological Recordings"
            href: Equip_physiological.qmd
          - text: "Experiment Administration"
            href: Experiment.qmd
          - text: "Integration of Signals"
            href: Integration.qmd

      - section: "Preprocessing"
        contents:
          - text: "Overview"
            href: Preprocessing_overview.qmd
          - text: "XDF Processing"
            href: 2_PREPROCESSING/1_XDF_PROCESSING/MML_XDF_Preprocessing.ipynb
          - text: "Audio-Video Synchronization"
            href: 2_PREPROCESSING/2_AudioVideo_Sync.ipynb

      - section: "Motion Tracking"
        contents:
          - text: "Overview"
            href: MT_overview.qmd
          - text: "Video Segmentation"
            href: 3_MOTION_TRACKING/1_Video_Segmentation/Donders MML_Video Split.ipynb
          - text: "Video Calibration"
            href: 3_MOTION_TRACKING/2_Video_Calibration/Calibration_anipose.ipynb
          - text: "Alternative 1: FreeMoCap"
            href: 3_MOTION_TRACKING/Alternative_1_FreeMoCap.qmd
          - text: "How to run FreeMoCap"
            href: 3_MOTION_TRACKING/Alternative_1_FreeMoCap_HowTo.qmd
          - text: "Alternative 2: Pose2sim"
            href: 3_MOTION_TRACKING/Alternative_2_Pose2sim.qmd

      - section: "Example of Analysis"
        contents:
          - text: "Overview"
            href: Example_Analysis.qmd
          - text: "Synchrony Analyses"
            href: 4b_SynchronyAnalyses/processing_and_visualization.ipynb
      
      - section: "Visualization"
        contents:
          - text: "Creating animations"
            href: 5_ANIMATIONS/Donkers_MML_Multimodal_Animations.ipynb



  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/MultiMobLab/Mobile-Multimodal-Lab
          - text: Report a Bug
            href: https://github.com/MultiMobLab/Mobile-Multimodal-Lab/issues

metadata:
  crossref:
    chapters: true


format:
  html:
    theme: lux
    highlight-style: github
    css: style.css






