---
title: "Mobile Multimodal Lab"
subtitle: "Lab Setup: Audio Recordings"
authors: Davide Ahmar, Šárka Kadavá, Wim Pouw
---

## Choosing the Audio Recording Setup

While both state-of-the-art, device-based MT systems and commercially avaliableavailable cameras typically include built-in microphones – which allow for simplified synchronization with the video recordings – the audio quality of these microphones is typically insufficient for high-resolution analyses of speech features such as pitch, intensity and prosody. Therefore, to obtain a good level of acoustic fidelity, in our MML we opted for a high-quality, head-mounted condenser microphone recording independently from the cameras. This design ensured consistent mouth-to-mic distance, reduced ambient interference, and reliable amplitude and frequency tracking across sessions. Additionally, to stream the audio signal to the LSL, we preferred a Linux-based PC over Windows or macOS because it enabled real-time streaming of low-latency, high precision audio thanks to its Advanced Linux Sound Architecture (ALSA).  

## Audio Recording Equipment

For the microphone, we employed a professional-grade, head-mounted condenser microphone (model: AKG C520, price ~€250) for each participants, as shown in Figure 1 C. The head-mounted configuration was important for maintaining a fixed distance between the participant’s mouth and the microphone capsule (essential for measurement of speech amplitude and prosodic features), whilst the cardioid polar pattern further focused sensitivity toward the speaker’s mouth and rejected off-axis environmental noise. Additionally, its built-in shock-mount system helped reduce the mechanical noise generated by body movements. Both microphones were powered via a XLR connection to a DAP PRE-202 low-noise, 2-channel digital amplifier (price: ~€90), which provided a +48V phantom power and included a low-cut filter to suppress low-frequency ambient noise. Input gain on the amplifier was manually fixed at 25% across all recordings to standardize signal levels. From the amplifier, the signal from each microphone was routed via two XLR-to-USB interface to two MINIX NEO z83-4 MAX Linux-based mini-PC (price: ~€170).  

## Audio Recording Procedures

To record and stream participants’ audio to the LSL, we used a custom-made Python script developed in collaboration with Technical Support Group (TSG) at the Donders Institute (see full script here). The script was executed on each MINIX Linux device and utilized the alsaaudio library to record each signal in mono at a sampling rate of 16 kHz, with 16-bit little-endian encoding optimized for low-latency buffering. The audio data from each MINIX was then streamed to the LSL using the pylsl library (Kothe, 2014), pushing small chunks of 160 data points timestamped against the system clock. The LSL then used the declared sampling rate and local system clock to reconstruct sample timing, allowing synchronization with other multimodal streams at sub-millisecond resolution. Additionally, to ensure data quality before acquisition, we useddeveloped a secondary Python script (see full script here) that allowed for real-time graphic visualization of the incoming audio stream. This script pulled the audio data back from LSL and plotted it on a live display that was continuously updated, enabling to verify waveform quality and monitor for issues such as noise artifacts, clipping, or dropouts.  

[here we can insert the code chunk]
