---
title: "Mobile Multimodal Lab"
subtitle: "Lab Setup: Physiological Recordings"
authors: Davide Ahmar, Šárka Kadavá, Wim Pouw
---

Here we say some intro

## Choosing the Physiological Setup

To complement the video and audio modalities in our MML setup, we also included physiological recordings of the EMG activity from participants’ biceps and triceps and thoracic respiration, with the goal of quantifying interpersonal physiological synchrony. Here, we wanted to prioritize a system that could support a modular sensor architecture, allowing researchers to buy only the biosensors relevant to their experimental goal. Additionally, we opted for a system that could transmit these signals wirelessly, thus granting participants free movements during the recordings. Finally, we needed something that could be easily integrated within the LSL system to ensure temporal synchronization with the other measures. Among all the avaliable proprietary options, we chose “PLUX Biosignals” recording system which, despite relying on proprietary hardware and (freely available) as it seemed to, meet all these requirements and offered a strong price/quality balance. We stress that the MML is not tied to any specific brand, and any LSL-compatible physiological system that meets these requirements can be incorporated into the setup. 

## Physiological Recording Equipment

As shown in Figure 1C, the equipment consisted of two (one per participant) “biosignalplux Hub” (price: ~€2000), each supporting up to 4 input channels and capable of sampling at rates of up to 3000 Hz per channel with 16-bit resolution (Note that an 8-channel biosignalplux Hub is also avaliable, costing ~€4000). These devices transmitted data wirelessly via BTbluetooth in real time to their respective recording computers (the same used for video recordings) using a dedicated BT bluetooth dongle. To record participants’ muscle activity, we used two surface EMG sensors per participant (price ~€170), one placed over the biceps brachii and one over the triceps brachii of the right arm, allowing us to monitor the activation patterns of both flexor and extensor muscle groups. The EMG sensors used a bipolar configuration, with two adhesive electrodes (positive and negative) optimized for low-noise acquisition of muscular activity by detecting bioelectrical signals transmitted along the muscle fibers during contraction. There was one ground electrode attached to the xxx. To record participants respiratory patterns, we used two piezoelectric respiration sensors (PZT, price ~€170) secured around each participants’ upper thorax with an adjustable elastic strap. This sensor measured the displacement caused by inhalation and exhalation via a flexible strip with a centrally embedded sensing membrane. 

## Physiological Recording Procedures

Before attaching the EMG sensors, participants’ skin was cleaned using an alcohol-based wipe and abrasive conductive gel (Nuprep) to reduce impedance and enhance signal quality. The two surface EMG electrodes were applied over the biceps brachii and triceps brachii of the dominant arm in a bipolar configuration, aligned along the longitudinal axis of each target muscle. The PZT belt was placed on the thorax at the level of the sternumaround the upper thorax, positioned so that the sensing element was centered over the chest. The elastic strap was adjusted to fit tightly without restricting breathing, ensuring that chest displacement was captured during inhalation and exhalation. Signal acquisition and LSL integration was managed using the OpenSignals (r)evolution software from biosignalsplux. Using the GUI of the software, we configured the EMGs and PZT channels to sample at 1000 Hz and visualized these signals in real time to verify  signal-to-noise ratio and appropriate signal amplitude across both EMG and respiration channels. 

The data streams were then broadcasted directly to the LSL using the software’s built-in LSL integration (see documentation here), resulting in two streams (one per participant) each containing the two raw EMG and one PZT time series synchronized with the other data modalities.  
