---
title: "Mobile Multimodal Lab"
subtitle: "Lab Setup: Integrating recordings via LabStreamLayer"
authors: Davide Ahmar, Šárka Kadavá, Wim Pouw
---

A major challenge in multimodal research relates to synchronization and integration of different recordings that operate on distinct hardware platforms, communicate via different software interfaces, rely on independent systems clocks, and sample at vastly different frequencies. A conventional approach to solve this challenge has typically relied on a host computer systematically broadcasting timestamped “marker events” to all recording systems associated with the various devices, which are then used to align the time series during post-processing. However, this method has several limitations: it requires extensive cabled connections, multiple independent recording computers, device-specific scripts for sending and receiving markers, decentralized data storage across systems, and time-consuming manual alignment of data streams after recording. Additionally, even minor issues like latency differences or hardware incompatibilities can introduce significant lags that can easily mis-align the time series, often without any explicit knowledge from the experimenters. For instance, video recordings are particularly prone to dropped frames during acquisition, which, unless properly accounted for by timestamping each frame, can result in de-synchronization that is difficult to detect and correct post hoc. To address these issues, in our MML we decided to implement the Lab Streaming Layer (Kothe et al., 2024), an open-sourced, cross-platform middleware system designed to enable real-time, sub-millisecond synchronization of heterogeneous data streams recorded from different devices. Unlike marker-based synchronization, the LSL creates a shared time base across all incoming data streams using each device’s local monotonic clock, allowing for built-in temporal alignment and centralized, integrated data collection. In addition to its accessible, affordable and portable nature, the LSL is also highly modular, supporting a wide range of recording devices - either through native compatibility or via custom-built LSL “outlet” scripts that stream data into the shared time framework.  

[A diagram of a video recording system]

## LSL Equipment and Assembly

At a system level, the LSL consists of the core liblsl library (ref? documentation?) – a cross-platform API running on major operating systems including Windows, macOS, and Linux– and associated GUI applications such as the LabRecorder (ref? documentation?). Functionally, the LSL is built on a simple architecture of Outlets and Inlets. Each recording device broadcasts its stream (i.e., Outlet) – either through a built-in system or via custom-made scripts – in the form of descriptive metadata (e.g., stream name, content, type, number of channels, etc.). Receiving applications (i.e., Inlet), such as LabRecorder, automatically detect these advertised streams and record them in real time. To achieve multimodal synchronization, the LSL leverages each machine’s local monotonic clock and continuously performs clock offset estimation between the Outlet and Inlet trhough periodic pinging, which are then used to created a shared time based across all streams with sub-millisecond alignment. This software architecture must be physically implemented through a wired local network, that can span multiple PC’s. In our setup, we constructed a multi-PC setup this by connecting all recording computers via Ethernet cables to a shared 5-port Gigabit LAN hub (model: NETGEAR GS305v3), which was in turn connected via Ethernet to the LSL recording computer, as shown in Figure 1B–C. 

## LSL Recording Procedures

As shown in Figure 1B&C, our MML setup comprised four recording computers, each configured as an LSL Outlet and assigned to a specific participant and modality. Two Windows machines were used to record thevideo and physiological data three video streams and Bluetooth-based physiological signals (EMG and respiration), each assigned to one participant.: the first handled three video streams and Bluetooth-based physiological signals (EMG and respiration) from P1, while the second did the same for P2. The two Linux machines were used to stream the audio data from each participant separately. P1 and P2, respectively. All Outlet streams were transmitted over the local LSL network to a fifth computer running the LabRecorder application (Inlet), which resolved and recorded the incoming streams into a single extendable data format (xdf) file with preserved metadata and a shared, sub-millisecond-accurate time base. Prior to each recording, the LabRecorder graphical interface allowed to verify the presence of and stability of all expected streams from both participants. Once confirmed, the interface allowed all streams to be recorded into a single .xdf file with a single button click.  

[here maybe screenshot of LabRecorder if we have]